import type {ScaleStep , OutputFormat } from '../types';

interface TokenOptions {
  steps: ScaleStep[]
  displayFont: string
  bodyFont: string
  monoFont: string
  format: OutputFormat
}

// CSS Custom Properties
function generateCSS(opts: TokenOptions): string {
  const { steps, displayFont, bodyFont, monoFont } = opts
  const lines: string[] = [
    ':root {',
    `  /* TypoScale — generated by typoscale.app */`,
    ``,
    `  /* Font Families */`,
    `  --font-display: '${displayFont}', Georgia, serif;`,
    `  --font-body: '${bodyFont}', system-ui, sans-serif;`,
    `  --font-mono: '${monoFont}', monospace;`,
    ``,
    `  /* Font Sizes */`,
    ...steps.map(s => `  --font-size-${s.name}: ${s.size}rem; /* ${s.sizePx}px */`),
    ``,
    `  /* Line Heights */`,
    ...steps.map(s => `  --line-height-${s.name}: ${s.lineHeight};`),
    ``,
    `  /* Letter Spacing */`,
    ...steps.map(s => `  --letter-spacing-${s.name}: ${s.letterSpacing};`),
    `}`,
  ]
  return lines.join('\n')
}

// Tailwind v3 config
function generateTailwindV3(opts: TokenOptions): string {
  const { steps, displayFont, bodyFont, monoFont } = opts
  const fontSizeEntries = steps
    .map(s => `      ${s.name}: ['${s.size}rem', { lineHeight: '${s.lineHeight}', letterSpacing: '${s.letterSpacing}' }],`)
    .join('\n')

  return `/** @type {import('tailwindcss').Config} */
// Generated by typoscale.app
module.exports = {
  theme: {
    extend: {
      fontFamily: {
        display: ['${displayFont}', 'Georgia', 'serif'],
        body: ['${bodyFont}', 'system-ui', 'sans-serif'],
        mono: ['${monoFont}', 'monospace'],
      },
      fontSize: {
${fontSizeEntries}
      },
    },
  },
}`
}

// Tailwind v4 (@theme)
function generateTailwindV4(opts: TokenOptions): string {
  const { steps, displayFont, bodyFont, monoFont } = opts
  const lines: string[] = [
    `/* Generated by typoscale.app */`,
    `@import "tailwindcss";`,
    ``,
    `@theme {`,
    `  /* Font Families */`,
    `  --font-family-display: '${displayFont}', Georgia, serif;`,
    `  --font-family-body: '${bodyFont}', system-ui, sans-serif;`,
    `  --font-family-mono: '${monoFont}', monospace;`,
    ``,
    `  /* Font Sizes */`,
    ...steps.map(s => `  --font-size-${s.name}: ${s.size}rem;`),
    ``,
    `  /* Line Heights */`,
    ...steps.map(s => `  --leading-${s.name}: ${s.lineHeight};`),
    ``,
    `  /* Letter Spacing */`,
    ...steps.map(s => `  --tracking-${s.name}: ${s.letterSpacing};`),
    `}`,
  ]
  return lines.join('\n')
}

// Style Dictionary JSON
function generateJSON(opts: TokenOptions): string {
  const { steps, displayFont, bodyFont, monoFont } = opts
  const tokens = {
    fontFamily: {
      display: { value: `'${displayFont}', Georgia, serif`, type: 'fontFamily' },
      body: { value: `'${bodyFont}', system-ui, sans-serif`, type: 'fontFamily' },
      mono: { value: `'${monoFont}', monospace`, type: 'fontFamily' },
    },
    fontSize: Object.fromEntries(
      steps.map(s => [s.name, { value: `${s.size}rem`, comment: `${s.sizePx}px`, type: 'fontSize' }])
    ),
    lineHeight: Object.fromEntries(
      steps.map(s => [s.name, { value: s.lineHeight, type: 'lineHeight' }])
    ),
    letterSpacing: Object.fromEntries(
      steps.map(s => [s.name, { value: s.letterSpacing, type: 'letterSpacing' }])
    ),
  }
  return JSON.stringify({ typography: tokens }, null, 2)
}

//Entry
export function generateTokens(opts: TokenOptions): string {
  switch (opts.format) {
    case 'css':          return generateCSS(opts)
    case 'tailwind-v3':  return generateTailwindV3(opts)
    case 'tailwind-v4':  return generateTailwindV4(opts)
    case 'json':         return generateJSON(opts)
  }
}

export function getLanguage(format: OutputFormat): string {
  switch (format) {
    case 'css':         return 'css'
    case 'tailwind-v3': return 'javascript'
    case 'tailwind-v4': return 'css'
    case 'json':        return 'json'
  }
}
